version: '3'
services:
  odp-redis:
    image: redis:7.2.1
    container_name: odp-redis
    ports:
      - "6379:6379"

  odp-spark-master:
    image: apache/spark:3.5.0
    container_name: odp-spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h odp-spark-master
    ports:
      - "8081:8080" # spark web ui port
      - "7077:7077" # spark master port

  odp-spark-worker-1:
    build:
      context: .
      dockerfile: spark-worker.Dockerfile
    container_name: odp-spark-worker-1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://odp-spark-master:7077

  odp-hadoop:
    image: sequenceiq/hadoop-docker:latest
    container_name: odp-hadoop
    command: /etc/bootstrap.sh -d
    ports:
      - "50070:50070" # HDFS NameNode web UI port (Expose to host)
      - "8088:8088"   # ResourceManager web UI port (Expose to host)
      - "9000:9000"   # HDFS default port (Expose to host)
