version: '3'
services:
  odp-redis:
    image: redis:latest
    container_name: odp-redis
    ports:
      - "6379:6379"

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    ports:
      - "8080:8080"

  spark-worker-1:
    image: apache/spark:3.5.0
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
