version: '3'
services:
  odp-redis:
    image: redis:7.2.1
    container_name: odp-redis
    ports:
      - "6379:6379"

  odp-spark-master:
    image: apache/spark:3.5.0
    container_name: odp-spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    ports:
      - "8080:8080"

  odp-spark-worker-1:
    image: apache/spark:3.5.0
    container_name: odp-spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
